version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/.github/workflows"
    target_branch: develop
    schedule:
      interval: daily
  - package-ecosystem: pip
    target_branch: develop
    directory: "/docs"
    schedule:
      interval: daily
  - package-ecosystem: pip
    target_branch: develop
    directory: "/"
    schedule:
      interval: daily
