name: PreRelease

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/poetry
            ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.cache-name }}-3.10-${{ hashFiles('pyproject.toml') }}-build
      - name: Install tooling
        run: |
          pip install --upgrade pip poetry twine
          pip --version
          poetry --version
          twine --version
      - name: Bump pre-release version
        run: |
          version=$(poetry version | awk '{ print $2 }' | cut -d- -f1) &&
          poetry version $version-dev$(date +%s)
      - name: Build Wheel
        run: |
          poetry build
      - name: Publish package on PyPI
        run: |
          twine upload \
            --repository-url=https://test.pypi.org/legacy/ \
            -u=__token__ \
            -p=${{ secrets.TEST_PYPI_TOKEN }} \
            --disable-progress-bar \
            dist/*
