name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/poetry
            ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.cache-name }}-3.10-${{ hashFiles('pyproject.toml') }}-build
      - name: Install tooling
        run: |
          pip install --upgrade pip poetry twine
          pip --version
          poetry --version
          twine --version
      - name: Bump version
        run: |
          poetry version ${{ github.event.release.tag_name }}
      - name: Build Wheel
        run: |
          poetry build
      - name: Publish package on PyPI
        run: |
          twine upload \
            -u=__token__ \
            -p=${{ secrets.PYPI_TOKEN }} \
            --disable-progress-bar \
            --skip-existing \
            dist/*
      - name: Commit bumped version to main branch
        run: |
          git fetch --all
          git checkout ${{ github.event.release.target_commitish }}
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git add pyproject.toml
          git commit -m "[skip ci] Bump to version ${{ github.event.release.tag_name }}"
          git push
